# Generated by Django 5.2.6 on 2025-09-30 21:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('text', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='qa/answers/')),
                ('is_correct', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'answers',
                'db_table': 'answer',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('collection_name', models.CharField(max_length=150)),
                ('language', models.TextField(default='uz', null=True)),
                ('collection_science_name', models.CharField(max_length=100)),
                ('since_id', models.IntegerField(blank=True, null=True)),
                ('max_attempts', models.IntegerField(default=1)),
                ('givenminutes', models.DurationField(default=datetime.timedelta(seconds=60))),
                ('amount_in_test', models.IntegerField()),
                ('admin_image', models.CharField(max_length=100, null=True)),
                ('admin_type', models.CharField(max_length=50, null=True)),
                ('admin_full_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('admin_email_address', models.CharField(db_index=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'archive_collection',
            },
        ),
        migrations.CreateModel(
            name='ArchiveQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('text', models.CharField(max_length=255)),
                ('collection_name', models.CharField(max_length=150)),
                ('language', models.TextField(default='uz', null=True)),
                ('collection_science_name', models.CharField(max_length=100)),
                ('since_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'archive_question',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('language', models.TextField(default='uz', null=True)),
                ('max_attempts', models.IntegerField(default=1)),
                ('givenminutes', models.DurationField(default=datetime.timedelta(seconds=60))),
                ('amount_in_test', models.IntegerField()),
            ],
            options={
                'db_table': 'collection',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'directory',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='qa/questions/')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user_image', models.CharField(max_length=100, null=True)),
                ('user_full_name', models.CharField(max_length=255, null=True)),
                ('user_email_address', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('user_type', models.CharField(max_length=50, null=True)),
                ('collection_name', models.CharField(max_length=150)),
                ('language', models.TextField(default='uz', null=True)),
                ('collection_science_name', models.CharField(max_length=100)),
                ('since_id', models.IntegerField(blank=True, null=True)),
                ('max_attempts', models.IntegerField(default=1)),
                ('givenminutes', models.DurationField(default=datetime.timedelta(seconds=60))),
                ('amount_in_test', models.IntegerField()),
                ('admin_image', models.CharField(max_length=100, null=True)),
                ('admin_type', models.CharField(max_length=50, null=True)),
                ('admin_full_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('admin_email_address', models.CharField(db_index=True, max_length=255, null=True, unique=True)),
                ('directory_name', models.CharField(max_length=128)),
                ('faculty_name', models.CharField(max_length=145)),
                ('stage', models.IntegerField(default=1)),
                ('group_name', models.CharField(max_length=150)),
                ('test_count', models.IntegerField()),
                ('result', models.IntegerField()),
                ('end_time', models.DateTimeField(null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qa.archive')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArchiveAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('question_text', models.TextField()),
                ('question_image', models.CharField(max_length=80, null=True)),
                ('is_checked', models.BooleanField()),
                ('collection_name', models.CharField(max_length=150)),
                ('language', models.TextField(default='uz', null=True)),
                ('collection_science_name', models.CharField(max_length=100)),
                ('since_id', models.IntegerField(blank=True, null=True)),
                ('directory_name', models.CharField(max_length=128)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qa.archiveanswer')),
            ],
            options={
                'db_table': 'archive_answer',
            },
        ),
    ]
