# Generated by Django 5.2.6 on 2025-09-29 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('qa', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives_user', to='users.user'),
        ),
        migrations.AddField(
            model_name='archivecollection',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.admin'),
        ),
        migrations.AddField(
            model_name='archivecollection',
            name='archive',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_archive_collections', to='qa.archive'),
        ),
        migrations.AddField(
            model_name='archivecollection',
            name='science',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='science_archive_collections', to='department.science'),
        ),
        migrations.AddField(
            model_name='archivequestion',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_collection_questions', to='qa.archivecollection'),
        ),
        migrations.AddField(
            model_name='archiveanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_question_archives', to='qa.archivequestion'),
        ),
        migrations.AddField(
            model_name='collection',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_collections', to='users.admin'),
        ),
        migrations.AddField(
            model_name='collection',
            name='science',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='science_collections', to='department.science'),
        ),
        migrations.AddField(
            model_name='archive',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_archives', to='qa.collection'),
        ),
        migrations.AddField(
            model_name='directory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qa.directory'),
        ),
        migrations.AddField(
            model_name='collection',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directory_collections', to='qa.directory'),
        ),
        migrations.AddField(
            model_name='question',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_questions', to='qa.collection'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_answers', to='qa.question'),
        ),
    ]
