# Generated by Django 5.2.6 on 2025-09-30 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('qa', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_collections', to='users.admin'),
        ),
        migrations.AddField(
            model_name='collection',
            name='science',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='science_collections', to='department.science'),
        ),
        migrations.AddField(
            model_name='directory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qa.directory'),
        ),
        migrations.AddField(
            model_name='collection',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directory_collections', to='qa.directory'),
        ),
        migrations.AddField(
            model_name='question',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_questions', to='qa.collection'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_answers', to='qa.question'),
        ),
    ]
